// reactapp/src/components/register.jsx
import React from 'react';
import axios from 'axios';
import { useNavigate } from 'react-router-dom';
import { useForm } from 'react-hook-form';
import { Link } from 'react-router-dom'
  const API_URL = process.env.REACT_APP_API_URL;

const Register = () => {
  const {
    register,
    handleSubmit,
    watch,
    formState: { errors, touchedFields },
  } = useForm({
    mode:'onBlur'
  });
const navigate = useNavigate();

  const onSubmit = async (data) => {

    try{
      const response = await axios.post(`${API_URL}/auth/register`, data);
            console.log('Register successful:', response.data);

    }
    
   catch (error) {
      console.error('Registration failed:', error.response?.data || error.message);
      alert(error.response?.data?.message || 'Registration failed');
    }
   };

  const password = watch('password');

  return (
    <div className="min-h-screen flex flex-col items-center justify-center bg-gray-100 space-y-6">
      {/* Logo */}
      <div className="flex justify-center">
        <img src="/logo.png" alt="Logo" className="h-12" /> {/* Replace with your <app-logo> equivalent */}
      </div>

      {/* Register Box */}
      <div className="bg-white shadow-md rounded px-8 py-6 w-full max-w-md">
        <h2 className="text-2xl font-bold mb-6 text-center">Sign Up</h2>

        <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
          <div>
            <input type="text" 
              className="w-full px-4 py-2 border rounded focus:outline-none focus:ring-2 focus:ring-blue-500"
              placeholder='username'
              {...register('name', { required: 'Name is required' })}
            />
            { errors.name && (
              <p className='text-red-500 text-sm mt-1'>{errors.name.message}</p>
            )}
          </div>
          <div>
            <input placeholder='email'  className="w-full px-4 py-2 border rounded focus:outline-none focus:ring-2 focus:ring-blue-500" type="email"
              {...register('email', {
                required: 'Email is required',
                pattern: {
                  value: /^\S+@\S+$/i,
                  message: 'Invalid email format.',
                }

              }


              )}
            />
            { errors.email &&
              <p className='text-red-500 text-sm mt-1'>{errors.email.message}</p>
            }
          </div>
          <div>
            <input type="password" placeholder='choose your password'  className="w-full px-4 py-2 border rounded focus:outline-none focus:ring-2 focus:ring-blue-500"
            {...register('password', {
              required:'choose your password'
            })}   
            
            />
            {errors.password &&
              <p className='text-red-500 text-sm mt-1'>{errors.password.message}</p>
            }
          </div>
          <div>
            <input type="password" placeholder="confirmPassword" className="w-full px-4 py-2 border rounded focus:outline-none focus:ring-2 focus:ring-blue-500"
              {...register('confirmPassword', {
                required: 'password should match',

                validate: (value) => value === password || 'Passwords do not match.'

              })}
            />
            {errors.confirmPassword &&
              <p className='text-red-500 text-sm mt-1'>{errors.confirmPassword.message}</p>
            }
          </div>
          <button type='submit' className='w-full bg-blue-600 py-2 rounded text-white hover:bg-blue-700'>Register</button>

        </form>

        <p className="mt-4 text-center text-sm">
          Already have an account?

        </p>

        <p className="text-left">
          <Link to="/" className="text-blue-600 hover:underline">
            Login
          </Link>
        </p>
      </div>
    </div>
  );
};

export default Register

// frontend/src/app/auth/register/register.component.ts
import { CommonModule, NgIf } from '@angular/common';
 import { Router } from '@angular/router';
import { ToastService } from '../../services/toast.service'; // adjust path

import { Component, ViewChild } from '@angular/core';
import { FormBuilder, FormGroup, FormsModule, ReactiveFormsModule, Validators,AbstractControl,ValidationErrors  } from '@angular/forms';
import { LogoComponent } from '../../shared/components/logo/logo.component';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-register',
  standalone: true,
  imports: [CommonModule, FormsModule, ReactiveFormsModule, NgIf,LogoComponent],
  templateUrl: './register.component.html',
  styleUrl: './register.component.scss'
})
export class RegisterComponent {

  registerForm = this.fb.group({
    name: ['', Validators.required],
    email: ['', [Validators.required, Validators.email]],
    password: ['', [Validators.required, Validators.minLength(6)]],
    confirmPassword: ['', Validators.required],
  }, { validators: this.passwordMatchValidator });
  

  constructor(private fb: FormBuilder,private router: Router, private authService:AuthService,
      private toast: ToastService

  ) {}

  passwordMatchValidator(group: AbstractControl): ValidationErrors | null {
    const password = group.get('password')?.value;
    const confirmPassword = group.get('confirmPassword')?.value;
    return password === confirmPassword ? null : { passwordsMismatch: true };
  }

   onRegister() {
  if (this.registerForm.invalid) {
    this.registerForm.markAllAsTouched();
    return;
  }

  const { name, email, password } = this.registerForm.value;

  // Ensure values are not null or undefined
  if (name && email && password) {
    const registerData = { name, email, password };

    this.authService.register(registerData).subscribe({
      next: () => {
        this.toast.show('Registered successfully!', 'success');
        this.registerForm.reset(); 

        this.router.navigate(['/auth/login']);
      },
      error: (err) => {
          const errorMessage = err?.error?.message || 'Registration failed';
          this.toast.show(errorMessage, 'error');
          this.registerForm.reset(); 
      }
    });
  }
}



   goToLogin() {
    // you can do extra checks, logging, etc. here
    this.router.navigate(['/auth/login']);
  }
}

<div class="min-h-screen flex flex-col items-center justify-center bg-gray-100 space-y-6">
    
  <!-- Centered Logo Outside the Box -->
  <div class="flex justify-center">
    <app-logo></app-logo>
  </div>

  <div class="bg-white shadow-md rounded px-8 py-6 w-full max-w-md">
    <h2 class="text-2xl font-bold mb-6 text-center">Sign Up</h2>

    <form [formGroup]="registerForm" (ngSubmit)="onRegister()" class="space-y-4">
      <!-- Name -->
      <div>
        <input
          type="text"
          formControlName="name"
          placeholder="Full Name"
          class="w-full px-4 py-2 border rounded focus:outline-none focus:ring-2 focus:ring-blue-500"
        />
        <div class="text-red-500 text-sm mt-1" *ngIf="registerForm.get('name')?.touched && registerForm.get('name')?.invalid">
          Name is required.
        </div>
      </div>

      <!-- Email -->
      <div>
        <input
          type="email"
          formControlName="email"
          placeholder="Email"
          class="w-full px-4 py-2 border rounded focus:outline-none focus:ring-2 focus:ring-blue-500"
        />
        <div class="text-red-500 text-sm mt-1" *ngIf="registerForm.get('email')?.touched && registerForm.get('email')?.invalid">
          <span *ngIf="registerForm.get('email')?.errors?.['required']">Email is required.</span>
          <span *ngIf="registerForm.get('email')?.errors?.['email']">Invalid email format.</span>
        </div>
      </div>

      <!-- Password -->
      <div>
        <input
          type="password"
          formControlName="password"
          placeholder="Password"
          class="w-full px-4 py-2 border rounded focus:outline-none focus:ring-2 focus:ring-blue-500"
        />
        <div class="text-red-500 text-sm mt-1" *ngIf="registerForm.get('password')?.touched && registerForm.get('password')?.invalid">
          <span *ngIf="registerForm.get('password')?.errors?.['required']">Password is required.</span>
          <span *ngIf="registerForm.get('password')?.errors?.['minlength']">Minimum 6 characters required.</span>
        </div>
      </div>
<div>
  <input type="password" formControlName="confirmPassword" placeholder="Confirm Password" class="w-full px-4 py-2 border rounded focus:outline-none focus:ring-2 focus:ring-blue-500" />
  <div class="text-red-500 text-sm mt-1" *ngIf="registerForm.get('confirmPassword')?.touched && registerForm.hasError('passwordsMismatch')">
    Passwords do not match.
  </div>
  <div class="text-red-500 text-sm mt-1" *ngIf="registerForm.get('confirmPassword')?.touched && registerForm.get('confirmPassword')?.hasError('required')">
    Confirm Password is required.
  </div>
</div>

      <!-- Submit -->
      <button type="submit" class="w-full bg-blue-600 hover:bg-blue-700 text-white font-semibold py-2 rounded">
        Register
      </button>
    </form>

    <p class="mt-4 text-center text-sm">
      Already have an account?
      <a (click)="goToLogin()" class="text-blue-600 hover:underline cursor-pointer">Login</a>
    </p>
  </div>
</div>
